# 运行阶段
FROM qicfan/qms-build-base:beta

ARG TARGETARCH
ARG TARGETOS

# 设置时区
ENV PATH=/app:$PATH
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_USER=qms
ENV DB_PASSWORD=qms123456
ENV DB_NAME=qms
ENV DB_SSLMODE=disable

# 添加用户和组（推荐方式）
RUN addgroup -g 12331 qms && \
    adduser -D -u 12331 -G qms qms
# 验证用户创建
RUN id qms
# 配置免密码 sudo
RUN echo 'qms ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
# 创建共享内存目录
RUN mkdir -p /dev/shm && chmod 1777 /dev/shm
# 设置工作目录
WORKDIR /app
# 复制可执行文件（根据架构自动选择）
COPY temp_build/QMediaSync_linux_${TARGETARCH}_exe ./QMediaSync
COPY backend/web_statics ./web_statics/
COPY backend/scripts ./scripts/
COPY backend/icon.ico .

RUN chmod +x /app/scripts/docker-entrypoint.sh
RUN chmod +x /app/scripts/watch_update.sh
RUN chmod +x /app/QMediaSync
RUN chmod 777 /app

VOLUME ["/app/config", "/media"]
# web ui端口
EXPOSE 12333
# 代理emby端口http
EXPOSE 8095
# 代理emby端口https
EXPOSE 8094
# 启动命令
CMD ["/bin/sh", "-c", "/app/scripts/docker-entrypoint.sh"]
