FROM alpine:3.20

RUN apk add --no-cache \
    ca-certificates \
    tzdata \
    ffmpeg \
    inotify-tools \
    postgresql15 && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV TZ=Asia/Shanghai
WORKDIR /app

CMD ["/bin/sh"]
