package helpers

type Country struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	NativeName string `json:"native_name"`
}

// Countries is an array of all ISO 3166-1 countries.
var Countries = []Country{
	{Code: "AF", Name: "阿富汗", NativeName: "افغانستان"},
	{Code: "AX", Name: "奥兰群岛", NativeName: "Åland"},
	{Code: "AL", Name: "阿尔巴尼亚", NativeName: "Shqipëria"},
	{Code: "DZ", Name: "阿尔及利亚", NativeName: "الجزائر"},
	{Code: "AS", Name: "美属萨摩亚", NativeName: "American Samoa"},
	{Code: "AD", Name: "安道尔", NativeName: "Andorra"},
	{Code: "AO", Name: "安哥拉", NativeName: "Angola"},
	{Code: "AI", Name: "安圭拉", NativeName: "Anguilla"},
	{Code: "AQ", Name: "南极洲", NativeName: "Antarctica"},
	{Code: "AG", Name: "安提瓜和巴布达", NativeName: "Antigua and Barbuda"},
	{Code: "AR", Name: "阿根廷", NativeName: "Argentina"},
	{Code: "AM", Name: "亚美尼亚", NativeName: "Հայաստան"},
	{Code: "AW", Name: "阿鲁巴", NativeName: "Aruba"},
	{Code: "AU", Name: "澳大利亚", NativeName: "Australia"},
	{Code: "AT", Name: "奥地利", NativeName: "Österreich"},
	{Code: "AZ", Name: "阿塞拜疆", NativeName: "Azərbaycan"},
	{Code: "BS", Name: "巴哈马", NativeName: "Bahamas"},
	{Code: "BH", Name: "巴林", NativeName: "البحرين"},
	{Code: "BD", Name: "孟加拉国", NativeName: "বাংলাদেশ"},
	{Code: "BB", Name: "巴巴多斯", NativeName: "Barbados"},
	{Code: "BY", Name: "白俄罗斯", NativeName: "Беларусь"},
	{Code: "BE", Name: "比利时", NativeName: "België"},
	{Code: "BZ", Name: "伯利兹", NativeName: "Belize"},
	{Code: "BJ", Name: "贝宁", NativeName: "Bénin"},
	{Code: "BM", Name: "百慕大", NativeName: "Bermuda"},
	{Code: "BT", Name: "不丹", NativeName: "འབྲུག"},
	{Code: "BO", Name: "玻利维亚", NativeName: "Bolivia"},
	{Code: "BQ", Name: "荷属加勒比区", NativeName: "Caribisch Nederland"},
	{Code: "BA", Name: "波斯尼亚和黑塞哥维那", NativeName: "Bosna i Hercegovina"},
	{Code: "BW", Name: "博茨瓦纳", NativeName: "Botswana"},
	{Code: "BV", Name: "布韦岛", NativeName: "Bouvetøya"},
	{Code: "BR", Name: "巴西", NativeName: "Brasil"},
	{Code: "IO", Name: "英属印度洋领地", NativeName: "British Indian Ocean Territory"},
	{Code: "BN", Name: "文莱", NativeName: "Brunei"},
	{Code: "BG", Name: "保加利亚", NativeName: "България"},
	{Code: "BF", Name: "布基纳法索", NativeName: "Burkina Faso"},
	{Code: "BI", Name: "布隆迪", NativeName: "Burundi"},
	{Code: "CV", Name: "佛得角", NativeName: "Cabo Verde"},
	{Code: "KH", Name: "柬埔寨", NativeName: "កម្ពុជា"},
	{Code: "CM", Name: "喀麦隆", NativeName: "Cameroun"},
	{Code: "CA", Name: "加拿大", NativeName: "Canada"},
	{Code: "KY", Name: "开曼群岛", NativeName: "Cayman Islands"},
	{Code: "CF", Name: "中非共和国", NativeName: "République centrafricaine"},
	{Code: "TD", Name: "乍得", NativeName: "Tchad"},
	{Code: "CL", Name: "智利", NativeName: "Chile"},
	{Code: "CN", Name: "中国", NativeName: "中国"},
	{Code: "CX", Name: "圣诞岛", NativeName: "Christmas Island"},
	{Code: "CC", Name: "科科斯群岛", NativeName: "Cocos (Keeling) Islands"},
	{Code: "CO", Name: "哥伦比亚", NativeName: "Colombia"},
	{Code: "KM", Name: "科摩罗", NativeName: "جزر القمر"},
	{Code: "CG", Name: "刚果共和国", NativeName: "République du Congo"},
	{Code: "CD", Name: "刚果民主共和国", NativeName: "République démocratique du Congo"},
	{Code: "CK", Name: "库克群岛", NativeName: "Cook Islands"},
	{Code: "CR", Name: "哥斯达黎加", NativeName: "Costa Rica"},
	{Code: "CI", Name: "科特迪瓦", NativeName: "Côte d'Ivoire"},
	{Code: "HR", Name: "克罗地亚", NativeName: "Hrvatska"},
	{Code: "CU", Name: "古巴", NativeName: "Cuba"},
	{Code: "CW", Name: "库拉索", NativeName: "Curaçao"},
	{Code: "CY", Name: "塞浦路斯", NativeName: "Κύπρος"},
	{Code: "CZ", Name: "捷克", NativeName: "Česko"},
	{Code: "DK", Name: "丹麦", NativeName: "Danmark"},
	{Code: "DJ", Name: "吉布提", NativeName: "Djibouti"},
	{Code: "DM", Name: "多米尼克", NativeName: "Dominica"},
	{Code: "DO", Name: "多米尼加共和国", NativeName: "República Dominicana"},
	{Code: "EC", Name: "厄瓜多尔", NativeName: "Ecuador"},
	{Code: "EG", Name: "埃及", NativeName: "مصر"},
	{Code: "SV", Name: "萨尔瓦多", NativeName: "El Salvador"},
	{Code: "GQ", Name: "赤道几内亚", NativeName: "Guinea Ecuatorial"},
	{Code: "ER", Name: "厄立特里亚", NativeName: "إريتريا"},
	{Code: "EE", Name: "爱沙尼亚", NativeName: "Eesti"},
	{Code: "SZ", Name: "斯威士兰", NativeName: "Eswatini"},
	{Code: "ET", Name: "埃塞俄比亚", NativeName: "ኢትዮጵያ"},
	{Code: "FK", Name: "福克兰群岛", NativeName: "Falkland Islands"},
	{Code: "FO", Name: "法罗群岛", NativeName: "Føroyar"},
	{Code: "FJ", Name: "斐济", NativeName: "Fiji"},
	{Code: "FI", Name: "芬兰", NativeName: "Suomi"},
	{Code: "FR", Name: "法国", NativeName: "France"},
	{Code: "GF", Name: "法属圭亚那", NativeName: "Guyane française"},
	{Code: "PF", Name: "法属波利尼西亚", NativeName: "Polynésie française"},
	{Code: "TF", Name: "法属南部领地", NativeName: "Terres australes françaises"},
	{Code: "GA", Name: "加蓬", NativeName: "Gabon"},
	{Code: "GM", Name: "冈比亚", NativeName: "Gambia"},
	{Code: "GE", Name: "格鲁吉亚", NativeName: "საქართველო"},
	{Code: "DE", Name: "德国", NativeName: "Deutschland"},
	{Code: "GH", Name: "加纳", NativeName: "Ghana"},
	{Code: "GI", Name: "直布罗陀", NativeName: "Gibraltar"},
	{Code: "GR", Name: "希腊", NativeName: "Ελλάδα"},
	{Code: "GL", Name: "格陵兰", NativeName: "Kalaallit Nunaat"},
	{Code: "GD", Name: "格林纳达", NativeName: "Grenada"},
	{Code: "GP", Name: "瓜德罗普", NativeName: "Guadeloupe"},
	{Code: "GU", Name: "关岛", NativeName: "Guam"},
	{Code: "GT", Name: "危地马拉", NativeName: "Guatemala"},
	{Code: "GG", Name: "根西岛", NativeName: "Guernsey"},
	{Code: "GN", Name: "几内亚", NativeName: "Guinée"},
	{Code: "GW", Name: "几内亚比绍", NativeName: "Guiné-Bissau"},
	{Code: "GY", Name: "圭亚那", NativeName: "Guyana"},
	{Code: "HT", Name: "海地", NativeName: "Haïti"},
	{Code: "HM", Name: "赫德岛和麦克唐纳群岛", NativeName: "Heard Island and McDonald Islands"},
	{Code: "VA", Name: "梵蒂冈", NativeName: "Città del Vaticano"},
	{Code: "HN", Name: "洪都拉斯", NativeName: "Honduras"},
	{Code: "HK", Name: "中国香港", NativeName: "香港"},
	{Code: "HU", Name: "匈牙利", NativeName: "Magyarország"},
	{Code: "IS", Name: "冰岛", NativeName: "Ísland"},
	{Code: "IN", Name: "印度", NativeName: "भारत"},
	{Code: "ID", Name: "印度尼西亚", NativeName: "Indonesia"},
	{Code: "IR", Name: "伊朗", NativeName: "ایران"},
	{Code: "IQ", Name: "伊拉克", NativeName: "العراق"},
	{Code: "IE", Name: "爱尔兰", NativeName: "Éire"},
	{Code: "IM", Name: "马恩岛", NativeName: "Isle of Man"},
	{Code: "IL", Name: "以色列", NativeName: "ישראל"},
	{Code: "IT", Name: "意大利", NativeName: "Italia"},
	{Code: "JM", Name: "牙买加", NativeName: "Jamaica"},
	{Code: "JP", Name: "日本", NativeName: "日本"},
	{Code: "JE", Name: "泽西岛", NativeName: "Jersey"},
	{Code: "JO", Name: "约旦", NativeName: "الأردن"},
	{Code: "KZ", Name: "哈萨克斯坦", NativeName: "Қазақстан"},
	{Code: "KE", Name: "肯尼亚", NativeName: "Kenya"},
	{Code: "KI", Name: "基里巴斯", NativeName: "Kiribati"},
	{Code: "KP", Name: "朝鲜", NativeName: "조선민주주의인민공화국"},
	{Code: "KR", Name: "韩国", NativeName: "대한민국"},
	{Code: "KW", Name: "科威特", NativeName: "الكويت"},
	{Code: "KG", Name: "吉尔吉斯斯坦", NativeName: "Кыргызстан"},
	{Code: "LA", Name: "老挝", NativeName: "ລາວ"},
	{Code: "LV", Name: "拉脱维亚", NativeName: "Latvija"},
	{Code: "LB", Name: "黎巴嫩", NativeName: "لبنان"},
	{Code: "LS", Name: "莱索托", NativeName: "Lesotho"},
	{Code: "LR", Name: "利比里亚", NativeName: "Liberia"},
	{Code: "LY", Name: "利比亚", NativeName: "ليبيا"},
	{Code: "LI", Name: "列支敦士登", NativeName: "Liechtenstein"},
	{Code: "LT", Name: "立陶宛", NativeName: "Lietuva"},
	{Code: "LU", Name: "卢森堡", NativeName: "Luxembourg"},
	{Code: "MO", Name: "中国澳门", NativeName: "澳門"},
	{Code: "MK", Name: "北马其顿", NativeName: "Северна Македонија"},
	{Code: "MG", Name: "马达加斯加", NativeName: "Madagasikara"},
	{Code: "MW", Name: "马拉维", NativeName: "Malawi"},
	{Code: "MY", Name: "马来西亚", NativeName: "Malaysia"},
	{Code: "MV", Name: "马尔代夫", NativeName: "ދިވެހިރާއްޖެ"},
	{Code: "ML", Name: "马里", NativeName: "Mali"},
	{Code: "MT", Name: "马耳他", NativeName: "Malta"},
	{Code: "MH", Name: "马绍尔群岛", NativeName: "Marshall Islands"},
	{Code: "MQ", Name: "马提尼克", NativeName: "Martinique"},
	{Code: "MR", Name: "毛里塔尼亚", NativeName: "موريتانيا"},
	{Code: "MU", Name: "毛里求斯", NativeName: "Maurice"},
	{Code: "YT", Name: "马约特", NativeName: "Mayotte"},
	{Code: "MX", Name: "墨西哥", NativeName: "México"},
	{Code: "FM", Name: "密克罗尼西亚", NativeName: "Micronesia"},
	{Code: "MD", Name: "摩尔多瓦", NativeName: "Moldova"},
	{Code: "MC", Name: "摩纳哥", NativeName: "Monaco"},
	{Code: "MN", Name: "蒙古", NativeName: "Монгол улс"},
	{Code: "ME", Name: "黑山", NativeName: "Crna Gora"},
	{Code: "MS", Name: "蒙特塞拉特", NativeName: "Montserrat"},
	{Code: "MA", Name: "摩洛哥", NativeName: "المغرب"},
	{Code: "MZ", Name: "莫桑比克", NativeName: "Moçambique"},
	{Code: "MM", Name: "缅甸", NativeName: "မြန်မာ"},
	{Code: "NA", Name: "纳米比亚", NativeName: "Namibia"},
	{Code: "NR", Name: "瑙鲁", NativeName: "Nauru"},
	{Code: "NP", Name: "尼泊尔", NativeName: "नेपाल"},
	{Code: "NL", Name: "荷兰", NativeName: "Nederland"},
	{Code: "NC", Name: "新喀里多尼亚", NativeName: "Nouvelle-Calédonie"},
	{Code: "NZ", Name: "新西兰", NativeName: "New Zealand"},
	{Code: "NI", Name: "尼加拉瓜", NativeName: "Nicaragua"},
	{Code: "NE", Name: "尼日尔", NativeName: "Niger"},
	{Code: "NG", Name: "尼日利亚", NativeName: "Nigeria"},
	{Code: "NU", Name: "纽埃", NativeName: "Niuē"},
	{Code: "NF", Name: "诺福克岛", NativeName: "Norfolk Island"},
	{Code: "MP", Name: "北马里亚纳群岛", NativeName: "Northern Mariana Islands"},
	{Code: "NO", Name: "挪威", NativeName: "Norge"},
	{Code: "OM", Name: "阿曼", NativeName: "عُمان"},
	{Code: "PK", Name: "巴基斯坦", NativeName: "پاکستان"},
	{Code: "PW", Name: "帕劳", NativeName: "Palau"},
	{Code: "PS", Name: "巴勒斯坦", NativeName: "فلسطين"},
	{Code: "PA", Name: "巴拿马", NativeName: "Panamá"},
	{Code: "PG", Name: "巴布亚新几内亚", NativeName: "Papua New Guinea"},
	{Code: "PY", Name: "巴拉圭", NativeName: "Paraguay"},
	{Code: "PE", Name: "秘鲁", NativeName: "Perú"},
	{Code: "PH", Name: "菲律宾", NativeName: "Pilipinas"},
	{Code: "PN", Name: "皮特凯恩群岛", NativeName: "Pitcairn Islands"},
	{Code: "PL", Name: "波兰", NativeName: "Polska"},
	{Code: "PT", Name: "葡萄牙", NativeName: "Portugal"},
	{Code: "PR", Name: "波多黎各", NativeName: "Puerto Rico"},
	{Code: "QA", Name: "卡塔尔", NativeName: "قطر"},
	{Code: "RE", Name: "留尼汪", NativeName: "La Réunion"},
	{Code: "RO", Name: "罗马尼亚", NativeName: "România"},
	{Code: "RU", Name: "俄罗斯", NativeName: "Россия"},
	{Code: "RW", Name: "卢旺达", NativeName: "Rwanda"},
	{Code: "BL", Name: "圣巴泰勒米", NativeName: "Saint-Barthélemy"},
	{Code: "SH", Name: "圣赫勒拿", NativeName: "Saint Helena"},
	{Code: "KN", Name: "圣基茨和尼维斯", NativeName: "Saint Kitts and Nevis"},
	{Code: "LC", Name: "圣卢西亚", NativeName: "Saint Lucia"},
	{Code: "MF", Name: "法属圣马丁", NativeName: "Saint-Martin"},
	{Code: "PM", Name: "圣皮埃尔和密克隆", NativeName: "Saint-Pierre-et-Miquelon"},
	{Code: "VC", Name: "圣文森特和格林纳丁斯", NativeName: "Saint Vincent and the Grenadines"},
	{Code: "WS", Name: "萨摩亚", NativeName: "Samoa"},
	{Code: "SM", Name: "圣马力诺", NativeName: "San Marino"},
	{Code: "ST", Name: "圣多美和普林西比", NativeName: "São Tomé e Príncipe"},
	{Code: "ST", Name: "圣多美和普林西比", NativeName: "São Tomé e Príncipe"},
	{Code: "SA", Name: "沙特阿拉伯", NativeName: "المملكة العربية السعودية"},
	{Code: "SN", Name: "塞内加尔", NativeName: "Sénégal"},
	{Code: "RS", Name: "塞尔维亚", NativeName: "Србија"},
	{Code: "SC", Name: "塞舌尔", NativeName: "Seychelles"},
	{Code: "SL", Name: "塞拉利昂", NativeName: "Sierra Leone"},
	{Code: "SG", Name: "新加坡", NativeName: "Singapore"},
	{Code: "SX", Name: "荷属圣马丁", NativeName: "Sint Maarten"},
	{Code: "SK", Name: "斯洛伐克", NativeName: "Slovensko"},
	{Code: "SI", Name: "斯洛文尼亚", NativeName: "Slovenija"},
	{Code: "SB", Name: "所罗门群岛", NativeName: "Solomon Islands"},
	{Code: "SO", Name: "索马里", NativeName: "Soomaaliya"},
	{Code: "ZA", Name: "南非", NativeName: "South Africa"},
	{Code: "GS", Name: "南乔治亚和南桑威奇群岛", NativeName: "South Georgia and the South Sandwich Islands"},
	{Code: "SS", Name: "南苏丹", NativeName: "South Sudan"},
	{Code: "ES", Name: "西班牙", NativeName: "España"},
	{Code: "LK", Name: "斯里兰卡", NativeName: "斯里兰卡语"},
	{Code: "SD", Name: "苏丹", NativeName: "苏丹语"},
	{Code: "SR", Name: "苏里南", NativeName: "Suriname"},
	{Code: "SJ", Name: "斯瓦尔巴和扬马延", NativeName: "Svalbard og Jan Mayen"},
	{Code: "SE", Name: "瑞典", NativeName: "Sverige"},
	{Code: "CH", Name: "瑞士", NativeName: "Schweiz"},
	{Code: "SY", Name: "叙利亚", NativeName: "سوريا"},
	{Code: "TW", Name: "中国台湾", NativeName: "台灣"},
	{Code: "TJ", Name: "塔吉克斯坦", NativeName: "Тоҷикистон"},
	{Code: "TZ", Name: "坦桑尼亚", NativeName: "Tanzania"},
	{Code: "TH", Name: "泰国", NativeName: "ประเทศไทย"},
	{Code: "TL", Name: "东帝汶", NativeName: "Timor-Leste"},
	{Code: "TG", Name: "多哥", NativeName: "Togo"},
	{Code: "TK", Name: "托克劳", NativeName: "Tokelau"},
	{Code: "TO", Name: "汤加", NativeName: "Tonga"},
	{Code: "TT", Name: "特立尼达和多巴哥", NativeName: "Trinidad and Tobago"},
	{Code: "TN", Name: "突尼斯", NativeName: "تونس"},
	{Code: "TR", Name: "土耳其", NativeName: "Türkiye"},
	{Code: "TM", Name: "土库曼斯坦", NativeName: "Türkmenistan"},
	{Code: "TC", Name: "特克斯和凯科斯群岛", NativeName: "Turks and Caicos Islands"},
	{Code: "TV", Name: "图瓦卢", NativeName: "Tuvalu"},
	{Code: "UG", Name: "乌干达", NativeName: "Uganda"},
	{Code: "UA", Name: "乌克兰", NativeName: "Україна"},
	{Code: "AE", Name: "阿联酋", NativeName: "الإمارات العربية المتحدة"},
	{Code: "GB", Name: "英国", NativeName: "United Kingdom"},
	{Code: "US", Name: "美国", NativeName: "United States"},
	{Code: "UM", Name: "美国本土外小岛屿", NativeName: "United States Minor Outlying Islands"},
	{Code: "UY", Name: "乌拉圭", NativeName: "Uruguay"},
	{Code: "UZ", Name: "乌兹别克斯坦", NativeName: "O'zbekiston"},
	{Code: "VU", Name: "瓦努阿图", NativeName: "Vanuatu"},
	{Code: "VE", Name: "委内瑞拉", NativeName: "Venezuela"},
	{Code: "VN", Name: "越南", NativeName: "Việt Nam"},
	{Code: "VG", Name: "英属维尔京群岛", NativeName: "British Virgin Islands"},
	{Code: "VI", Name: "美属维尔京群岛", NativeName: "United States Virgin Islands"},
	{Code: "WF", Name: "瓦利斯和富图纳", NativeName: "Wallis et Futuna"},
	{Code: "EH", Name: "西撒哈拉", NativeName: "الصحراء الغربية"},
	{Code: "YE", Name: "也门", NativeName: "اليمن"},
	{Code: "ZM", Name: "赞比亚", NativeName: "Zambia"},
	{Code: "ZW", Name: "津巴布韦", NativeName: "Zimbabwe"},
}
var CountryMap map[string]string

func GetCountryName(code string) string {
	if CountryMap == nil {
		CountryMap = make(map[string]string)
		for _, country := range Countries {
			CountryMap[country.Code] = country.Name
		}
	}
	if name, ok := CountryMap[code]; ok {
		return name
	}
	return ""
}
