package helpers

// Language is an ISO 639-1 language with code, name and native name.
type Language struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	NativeName string `json:"native_name"`
}

// Languages is an array of all ISO 639-1 languages.
var Languages = []Language{
	{Code: "aa", Name: "阿法尔语", NativeName: "Afaraf"},
	{Code: "ab", Name: "阿布哈兹语", NativeName: "Аҧсуа бызшәа"},
	{Code: "ae", Name: "阿维斯陀语", NativeName: "Avesta"},
	{Code: "af", Name: "南非荷兰语", NativeName: "Afrikaans"},
	{Code: "ak", Name: "阿肯语", NativeName: "Akan"},
	{Code: "am", Name: "阿姆哈拉语", NativeName: "አማርኛ"},
	{Code: "an", Name: "阿拉贡语", NativeName: "Aragonés"},
	{Code: "ar", Name: "阿拉伯语", NativeName: "اللغة العربية"},
	{Code: "as", Name: "阿萨姆语", NativeName: "অসমীয়া"},
	{Code: "av", Name: "阿瓦尔语", NativeName: "Авар мацӀ"},
	{Code: "ay", Name: "艾马拉语", NativeName: "Aymar aru"},
	{Code: "az", Name: "阿塞拜疆语", NativeName: "Azərbaycan dili"},
	{Code: "ba", Name: "巴什基尔语", NativeName: "Башҡорт теле"},
	{Code: "be", Name: "白俄罗斯语", NativeName: "Беларуская мова"},
	{Code: "bg", Name: "保加利亚语", NativeName: "Български език"},
	{Code: "bi", Name: "比斯拉马语", NativeName: "Bislama"},
	{Code: "bm", Name: "班巴拉语", NativeName: "Bamanankan"},
	{Code: "bn", Name: "孟加拉语", NativeName: "বাংলা"},
	{Code: "bo", Name: "藏语", NativeName: "བོད་ཡིག"},
	{Code: "br", Name: "布列塔尼语", NativeName: "Brezhoneg"},
	{Code: "bs", Name: "波斯尼亚语", NativeName: "Bosanski jezik"},
	{Code: "ca", Name: "加泰罗尼亚语", NativeName: "Català"},
	{Code: "ce", Name: "车臣语", NativeName: "Нохчийн мотт"},
	{Code: "ch", Name: "查莫罗语", NativeName: "Chamoru"},
	{Code: "co", Name: "科西嘉语", NativeName: "Corsu"},
	{Code: "cr", Name: "克里语", NativeName: "ᓀᐦᐃᔭᐍᐏᐣ"},
	{Code: "cs", Name: "捷克语", NativeName: "Čeština"},
	{Code: "cu", Name: "古教会斯拉夫语", NativeName: "Ѩзыкъ словѣньскъ"},
	{Code: "cv", Name: "楚瓦什语", NativeName: "Чӑваш чӗлхи"},
	{Code: "cy", Name: "威尔士语", NativeName: "Cymraeg"},
	{Code: "da", Name: "丹麦语", NativeName: "Dansk"},
	{Code: "de", Name: "德语", NativeName: "Deutsch"},
	{Code: "dv", Name: "迪维希语", NativeName: "Dhivehi"},
	{Code: "dz", Name: "宗卡语", NativeName: "རྫོང་ཁ"},
	{Code: "ee", Name: "埃维语", NativeName: "Eʋegbe"},
	{Code: "el", Name: "希腊语", NativeName: "Ελληνικά"},
	{Code: "en", Name: "英语", NativeName: "English"},
	{Code: "eo", Name: "世界语", NativeName: "Esperanto"},
	{Code: "es", Name: "西班牙语", NativeName: "Español"},
	{Code: "et", Name: "爱沙尼亚语", NativeName: "Eesti"},
	{Code: "eu", Name: "巴斯克语", NativeName: "Euskara"},
	{Code: "fa", Name: "波斯语", NativeName: "فارسی"},
	{Code: "ff", Name: "富拉语", NativeName: "Fulfulde"},
	{Code: "fi", Name: "芬兰语", NativeName: "Suomi"},
	{Code: "fj", Name: "斐济语", NativeName: "Vakaviti"},
	{Code: "fo", Name: "法罗语", NativeName: "Føroyskt"},
	{Code: "fr", Name: "法语", NativeName: "Français"},
	{Code: "fy", Name: "西弗里西亚语", NativeName: "Frysk"},
	{Code: "ga", Name: "爱尔兰语", NativeName: "Gaeilge"},
	{Code: "gd", Name: "苏格兰盖尔语", NativeName: "Gàidhlig"},
	{Code: "gl", Name: "加利西亚语", NativeName: "Galego"},
	{Code: "gn", Name: "瓜拉尼语", NativeName: "Avañeẽ"},
	{Code: "gu", Name: "古吉拉特语", NativeName: "ગુજરાતી"},
	{Code: "gv", Name: "马恩语", NativeName: "Gaelg"},
	{Code: "ha", Name: "豪萨语", NativeName: "هَوُسَ"},
	{Code: "he", Name: "希伯来语", NativeName: "עברית"},
	{Code: "hi", Name: "印地语", NativeName: "हिन्दी"},
	{Code: "ho", Name: "希里莫图语", NativeName: "Hiri Motu"},
	{Code: "hr", Name: "克罗地亚语", NativeName: "Hrvatski jezik"},
	{Code: "ht", Name: "海地克里奥尔语", NativeName: "Kreyòl ayisyen"},
	{Code: "hu", Name: "匈牙利语", NativeName: "Magyar"},
	{Code: "hy", Name: "亚美尼亚语", NativeName: "Հայերեն"},
	{Code: "hz", Name: "赫雷罗语", NativeName: "Otjiherero"},
	{Code: "ia", Name: "国际语", NativeName: "Interlingua"},
	{Code: "id", Name: "印度尼西亚语", NativeName: "Indonesian"},
	{Code: "ie", Name: "西方国际语", NativeName: "Interlingue"},
	{Code: "ig", Name: "伊博语", NativeName: "Asụsụ Igbo"},
	{Code: "ii", Name: "彝语", NativeName: "ꆈꌠ꒿ Nuosuhxop"},
	{Code: "ik", Name: "因纽皮雅特语", NativeName: "Iñupiaq"},
	{Code: "io", Name: "伊多语", NativeName: "Ido"},
	{Code: "is", Name: "冰岛语", NativeName: "Íslenska"},
	{Code: "it", Name: "意大利语", NativeName: "Italiano"},
	{Code: "iu", Name: "因纽特语", NativeName: "ᐃᓄᒃᑎᑐᑦ"},
	{Code: "ja", Name: "日语", NativeName: "日本語"},
	{Code: "jv", Name: "爪哇语", NativeName: "Basa Jawa"},
	{Code: "ka", Name: "格鲁吉亚语", NativeName: "Ქართული"},
	{Code: "kg", Name: "刚果语", NativeName: "Kikongo"},
	{Code: "ki", Name: "基库尤语", NativeName: "Gĩkũyũ"},
	{Code: "kj", Name: "宽亚玛语", NativeName: "Kuanyama"},
	{Code: "kk", Name: "哈萨克语", NativeName: "Қазақ тілі"},
	{Code: "kl", Name: "格陵兰语", NativeName: "Kalaallisut"},
	{Code: "km", Name: "高棉语", NativeName: "ខេមរភាសា"},
	{Code: "kn", Name: "卡纳达语", NativeName: "ಕನ್ನಡ"},
	{Code: "ko", Name: "韩语", NativeName: "한국어"},
	{Code: "kr", Name: "卡努里语", NativeName: "Kanuri"},
	{Code: "ks", Name: "克什米尔语", NativeName: "कश्मीरी"},
	{Code: "ku", Name: "库尔德语", NativeName: "Kurdî"},
	{Code: "kv", Name: "科米语", NativeName: "Коми кыв"},
	{Code: "kw", Name: "康沃尔语", NativeName: "Kernewek"},
	{Code: "ky", Name: "吉尔吉斯语", NativeName: "Кыргызча"},
	{Code: "la", Name: "拉丁语", NativeName: "Latine"},
	{Code: "lb", Name: "卢森堡语", NativeName: "Lëtzebuergesch"},
	{Code: "lg", Name: "干达语", NativeName: "Luganda"},
	{Code: "li", Name: "林堡语", NativeName: "Limburgs"},
	{Code: "ln", Name: "林加拉语", NativeName: "Lingála"},
	{Code: "lo", Name: "老挝语", NativeName: "ພາສາ"},
	{Code: "lt", Name: "立陶宛语", NativeName: "Lietuvių kalba"},
	{Code: "lu", Name: "卢巴-加丹加语", NativeName: "Tshiluba"},
	{Code: "lv", Name: "拉脱维亚语", NativeName: "Latviešu valoda"},
	{Code: "mg", Name: "马尔加什语", NativeName: "Fiteny malagasy"},
	{Code: "mh", Name: "马绍尔语", NativeName: "Kajin M̧ajeļ"},
	{Code: "mi", Name: "毛利语", NativeName: "Te reo Māori"},
	{Code: "mk", Name: "马其顿语", NativeName: "Македонски јазик"},
	{Code: "ml", Name: "马拉雅拉姆语", NativeName: "മലയാളം"},
	{Code: "mn", Name: "蒙古语", NativeName: "Монгол хэл"},
	{Code: "mr", Name: "马拉地语", NativeName: "मराठी"},
	{Code: "ms", Name: "马来语", NativeName: "马来语"},
	{Code: "mt", Name: "马耳他语", NativeName: "Malti"},
	{Code: "my", Name: "缅甸语", NativeName: "ဗမာစာ"},
	{Code: "na", Name: "瑙鲁语", NativeName: "Ekakairũ Naoero"},
	{Code: "nb", Name: "挪威博克马尔语", NativeName: "Norsk bokmål"},
	{Code: "nd", Name: "北恩德贝莱语", NativeName: "IsiNdebele"},
	{Code: "ne", Name: "尼泊尔语", NativeName: "नेपाली"},
	{Code: "ng", Name: "恩东加语", NativeName: "Owambo"},
	{Code: "nl", Name: "荷兰语", NativeName: "Nederlands"},
	{Code: "nn", Name: "挪威尼诺斯克语", NativeName: "Norsk nynorsk"},
	{Code: "no", Name: "挪威语", NativeName: "Norsk"},
	{Code: "nr", Name: "南恩德贝莱语", NativeName: "IsiNdebele"},
	{Code: "nv", Name: "纳瓦霍语", NativeName: "Diné bizaad"},
	{Code: "ny", Name: "齐切瓦语", NativeName: "ChiCheŵa"},
	{Code: "oc", Name: "奥克语", NativeName: "Occitan"},
	{Code: "oj", Name: "奥吉布瓦语", NativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
	{Code: "om", Name: "奥罗莫语", NativeName: "Afaan Oromoo"},
	{Code: "or", Name: "奥里亚语", NativeName: "ଓଡ଼ିଆ"},
	{Code: "os", Name: "奥塞梯语", NativeName: "Ирон æвзаг"},
	{Code: "pa", Name: "旁遮普语", NativeName: "ਪੰਜਾਬੀ"},
	{Code: "pi", Name: "巴利语", NativeName: "पाऴि"},
	{Code: "pl", Name: "波兰语", NativeName: "Język polski"},
	{Code: "ps", Name: "普什图语", NativeName: "پښتو"},
	{Code: "pt", Name: "葡萄牙语", NativeName: "Português"},
	{Code: "qu", Name: "克丘亚语", NativeName: "Runa Simi"},
	{Code: "rm", Name: "罗曼什语", NativeName: "Rumantsch grischun"},
	{Code: "rn", Name: "隆迪语", NativeName: "Ikirundi"},
	{Code: "ro", Name: "罗马尼亚语", NativeName: "Română"},
	{Code: "ru", Name: "俄语", NativeName: "Русский"},
	{Code: "rw", Name: "卢旺达语", NativeName: "Ikinyarwanda"},
	{Code: "sa", Name: "梵语", NativeName: "संस्कृतम्"},
	{Code: "sc", Name: "撒丁语", NativeName: "Sardu"},
	{Code: "sd", Name: "信德语", NativeName: "सिन्धी"},
	{Code: "se", Name: "北萨米语", NativeName: "Davvisámegiella"},
	{Code: "sg", Name: "桑戈语", NativeName: "Yângâ tî sängö"},
	{Code: "si", Name: "僧伽罗语", NativeName: "සිංහල"},
	{Code: "sk", Name: "斯洛伐克语", NativeName: "Slovenčina"},
	{Code: "sl", Name: "斯洛文尼亚语", NativeName: "Slovenski jezik"},
	{Code: "sm", Name: "萨摩亚语", NativeName: "Gagana faa Samoa"},
	{Code: "sn", Name: "绍纳语", NativeName: "ChiShona"},
	{Code: "so", Name: "索马里语", NativeName: "Soomaaliga"},
	{Code: "sq", Name: "阿尔巴尼亚语", NativeName: "Shqip"},
	{Code: "sr", Name: "塞尔维亚语", NativeName: "Српски језик"},
	{Code: "ss", Name: "斯瓦蒂语", NativeName: "SiSwati"},
	{Code: "st", Name: "南索托语", NativeName: "Sesotho"},
	{Code: "su", Name: "巽他语", NativeName: "Basa Sunda"},
	{Code: "sv", Name: "瑞典语", NativeName: "Svenska"},
	{Code: "sw", Name: "斯瓦希里语", NativeName: "Kiswahili"},
	{Code: "ta", Name: "泰米尔语", NativeName: "தமிழ்"},
	{Code: "te", Name: "泰卢固语", NativeName: "తెలుగు"},
	{Code: "tg", Name: "塔吉克语", NativeName: "Тоҷикӣ"},
	{Code: "th", Name: "泰语", NativeName: "ไทย"},
	{Code: "ti", Name: "提格里尼亚语", NativeName: "ትግርኛ"},
	{Code: "tk", Name: "土库曼语", NativeName: "Türkmen"},
	{Code: "tl", Name: "他加禄语", NativeName: "Wikang Tagalog"},
	{Code: "tn", Name: "茨瓦纳语", NativeName: "Setswana"},
	{Code: "to", Name: "汤加语", NativeName: "Faka Tonga"},
	{Code: "tr", Name: "土耳其语", NativeName: "Türkçe"},
	{Code: "ts", Name: "聪加语", NativeName: "Xitsonga"},
	{Code: "tt", Name: "鞑靼语", NativeName: "Татар теле"},
	{Code: "tw", Name: "契维语", NativeName: "Twi"},
	{Code: "ty", Name: "塔希提语", NativeName: "Reo Tahiti"},
	{Code: "ug", Name: "维吾尔语", NativeName: "维吾尔语"},
	{Code: "uk", Name: "乌克兰语", NativeName: "Українська"},
	{Code: "ur", Name: "乌尔都语", NativeName: "اردو"},
	{Code: "uz", Name: "乌兹别克语", NativeName: "Ўзбек"},
	{Code: "ve", Name: "文达语", NativeName: "Tshivenḓa"},
	{Code: "vi", Name: "越南语", NativeName: "Tiếng Việt"},
	{Code: "vo", Name: "沃拉普克语", NativeName: "Volapük"},
	{Code: "wa", Name: "瓦隆语", NativeName: "Walon"},
	{Code: "wo", Name: "沃洛夫语", NativeName: "Wollof"},
	{Code: "xh", Name: "科萨语", NativeName: "IsiXhosa"},
	{Code: "yi", Name: "意第绪语", NativeName: "ייִדיש"},
	{Code: "yo", Name: "约鲁巴语", NativeName: "Yorùbá"},
	{Code: "za", Name: "壮语", NativeName: "Saɯ cueŋƅ"},
	{Code: "zh", Name: "普通话", NativeName: "普通话"},
	{Code: "cn", Name: "粤语", NativeName: "粤语"},
	{Code: "zu", Name: "祖鲁语", NativeName: "IsiZulu"},
}
var LanguageMap map[string]string

func GetLanguageName(code string) string {
	if LanguageMap == nil {
		LanguageMap = make(map[string]string)
		for _, language := range Languages {
			LanguageMap[language.Code] = language.Name
		}
	}
	if name, ok := LanguageMap[code]; ok {
		return name
	}
	return ""
}
